### ISSUE TITLE
The search reloads the website

### ISSUE THREAD

**Issue by saveli** [mirkobrombin/Amusiz#4]
Using the search bar stops the current playing song, resets it to the beginning, and shows the login animation (amazon music logo fading in and out) in the center view. 
Both interrupting listening to music and being able to use the center view for the duration of the animation, roughly 3 seconds.

**Comment by mirkobrombin** [comment]
The search actually opens a new link and the "workflow" is that of Amazon Music, not Amusiz. What I can try to do is inject a js script to take advantage of the site search instead of changing url.

This IS NOT A NICE WAY, it is an Amazon product tamper but it may be the only solution. I'll think about it and see if I can implement it.

**Comment by saveli** [comment]
This is weird, since in the web version I don't have these problems/interrupts.

**Comment by mirkobrombin** [comment]
> This is weird, since in the web version I don't have these problems/interrupts.

As the website uses a js function to get the results. We change the uri with the search terms.
